# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "OpenEnv"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_flute"

engines:
  serializer:
    JSON:
      allow_blessed: '1'
  session:
    DBIC:
      db_connection_name: default
  template:
    template_flute:
      filters:
        currency:
          options:
            int_curr_symbol: "$"
        date:
          class: "Template::Flute::Filter::Date"
          options:
            format: '%x %R'
            strict:
              empty: 0
        date_only:
          class: "Template::Flute::Filter::Date"
          options:
            format: '%x'
            strict:
              empty: 0
        time_only:
          class: "Template::Flute::Filter::Date"
          options:
            format: '%R'
            strict:
              empty: 0
plugins:
  Auth::Extensible:
    disable_roles: 0
    exit_page: '/'
    no_login_handler: 1
    login_page: /login
    logout_page: /logout
    denied_page: /login/denied
    no_default_pages: 1
    no_api_change_warning: 1
    realms:
      users:
        provider: 'DBIC'
        db_connection_name: 'default'
        users_resultset: User
        roles_resultset: Role
        user_roles_resultset: UserRole
        roles_relationship: roles
        roles_role_column: name
        users_username_column: username
        users_password_column: password
        users_password_check: check_password
  DBIC:
    default:
      user: openenv
      schema_class: OpenEnv::Schema


